SHOW DATABASES;
SHOW TABLES;

CREATE TABLE df LIKE dataf;
INSERT INTO df 
SELECT * FROM dataf;
SELECT * FROM df;


-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) revenue FROM df 
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT * FROM df
WHERE discount_applied = "Yes" AND 
purchase_amount >= (SELECT AVG(purchase_amount) FROM df);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating), 2) review_rating_for_item FROM df 
GROUP BY item_purchased  
ORDER BY review_rating_for_item DESC 
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT * FROM df;

SELECT shipping_type, AVG(purchase_amount) Average_purchase_amount 
FROM df WHERE shipping_type = 'Standard'
union
SELECT shipping_type, AVG(purchase_amount)  Average_purchase_amount 
FROM df WHERE shipping_type = 'Express';

SELECT shipping_type, AVG(purchase_amount)  Average_purchase_amount FROM df 
WHERE shipping_type = 'Standard' OR shipping_type = 'Express'
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT subscription_status, AVG(purchase_amount) average_purchase_amount, 
SUM(purchase_amount) sum_of_purchase_amount FROM df 
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT * FROM df;
SELECT t1.item_purchased, (discounted_items * 100)/(discounted_items + non_discounted_items) percent FROM
(SELECT item_purchased, discount_applied, COUNT(item_purchased) discounted_items FROM df 
WHERE discount_applied = 'Yes' 
GROUP BY item_purchased, discount_applied) t1
JOIN 
(SELECT item_purchased, discount_applied, COUNT(item_purchased) non_discounted_items FROM df 
WHERE discount_applied = 'No' 
GROUP BY item_purchased, discount_applied) t2 
ON t1.item_purchased = t2.item_purchased 
ORDER BY percent DESC 
LIMIT 5;


SELECT item_purchased, ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*)) percent FROM df 
GROUP BY item_purchased 
ORDER BY percent DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

SELECT * FROM df;

WITH customer_type AS (
SELECT customer_id, previous_purchases, 
CASE 
WHEN previous_purchases = 1 THEN 'New' 
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning' 
WHEN previous_purchases > 10 THEN 'Loyal'
END AS customer_segment FROM df)
SELECT customer_segment, COUNT(*) number_of_customers 
FROM customer_type 
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
SELECT * FROM df;

WITH cte AS(
SELECT category, item_purchased, SUM(purchase_amount) each_item_purchase_amount, 
ROW_NUMBER() OVER(PARTITION BY category ORDER BY SUM(purchase_amount) DESC) position FROM df 
GROUP BY category, item_purchased
)
SELECT * FROM cte WHERE position <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT * FROM df;

SELECT subscription_status, COUNT(subscription_status) repeated_buyers FROM df WHERE previous_purchases > 5 AND subscription_status = 'Yes'
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT age_group, SUM(purchase_amount) total_revenue_by_age_group FROM df 
GROUP BY age_group 
ORDER BY total_revenue_by_age_group DESC;